// ISO 4217 currency codes (full list, prefilled per metadata-v2 spec).
// Used by Settings → App Identity (base currency dropdown) and by the
// Currency dimension setup. Maps to CurrencyCatalog table.

export type IsoCurrency = {
  code: string;       // 3-letter ISO 4217
  name: string;
  symbol: string;
  decimals: number;
  region?: string;
};

export const ISO_4217: IsoCurrency[] = [
  { code: "AED", name: "UAE Dirham",          symbol: "د.إ",  decimals: 2, region: "Middle East" },
  { code: "AFN", name: "Afghan Afghani",      symbol: "؋",     decimals: 2, region: "Asia" },
  { code: "ALL", name: "Albanian Lek",        symbol: "L",     decimals: 2, region: "Europe" },
  { code: "AMD", name: "Armenian Dram",       symbol: "֏",     decimals: 2, region: "Asia" },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", decimals: 2, region: "Americas" },
  { code: "AOA", name: "Angolan Kwanza",      symbol: "Kz",    decimals: 2, region: "Africa" },
  { code: "ARS", name: "Argentine Peso",      symbol: "$",     decimals: 2, region: "Americas" },
  { code: "AUD", name: "Australian Dollar",   symbol: "$",     decimals: 2, region: "Oceania" },
  { code: "AWG", name: "Aruban Florin",       symbol: "ƒ",     decimals: 2, region: "Americas" },
  { code: "AZN", name: "Azerbaijani Manat",   symbol: "₼",     decimals: 2, region: "Asia" },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark", symbol: "KM", decimals: 2, region: "Europe" },
  { code: "BBD", name: "Barbadian Dollar",    symbol: "$",     decimals: 2, region: "Americas" },
  { code: "BDT", name: "Bangladeshi Taka",    symbol: "৳",     decimals: 2, region: "Asia" },
  { code: "BGN", name: "Bulgarian Lev",       symbol: "лв",    decimals: 2, region: "Europe" },
  { code: "BHD", name: "Bahraini Dinar",      symbol: ".د.ب", decimals: 3, region: "Middle East" },
  { code: "BIF", name: "Burundian Franc",     symbol: "Fr",    decimals: 0, region: "Africa" },
  { code: "BMD", name: "Bermudian Dollar",    symbol: "$",     decimals: 2, region: "Americas" },
  { code: "BND", name: "Brunei Dollar",       symbol: "$",     decimals: 2, region: "Asia" },
  { code: "BOB", name: "Bolivian Boliviano",  symbol: "Bs.",   decimals: 2, region: "Americas" },
  { code: "BRL", name: "Brazilian Real",      symbol: "R$",    decimals: 2, region: "Americas" },
  { code: "BSD", name: "Bahamian Dollar",     symbol: "$",     decimals: 2, region: "Americas" },
  { code: "BTN", name: "Bhutanese Ngultrum",  symbol: "Nu.",   decimals: 2, region: "Asia" },
  { code: "BWP", name: "Botswana Pula",       symbol: "P",     decimals: 2, region: "Africa" },
  { code: "BYN", name: "Belarusian Ruble",    symbol: "Br",    decimals: 2, region: "Europe" },
  { code: "BZD", name: "Belize Dollar",       symbol: "BZ$",   decimals: 2, region: "Americas" },
  { code: "CAD", name: "Canadian Dollar",     symbol: "$",     decimals: 2, region: "Americas" },
  { code: "CDF", name: "Congolese Franc",     symbol: "Fr",    decimals: 2, region: "Africa" },
  { code: "CHF", name: "Swiss Franc",         symbol: "Fr",    decimals: 2, region: "Europe" },
  { code: "CLP", name: "Chilean Peso",        symbol: "$",     decimals: 0, region: "Americas" },
  { code: "CNY", name: "Chinese Yuan",        symbol: "¥",     decimals: 2, region: "Asia" },
  { code: "COP", name: "Colombian Peso",      symbol: "$",     decimals: 2, region: "Americas" },
  { code: "CRC", name: "Costa Rican Colón",   symbol: "₡",     decimals: 2, region: "Americas" },
  { code: "CUP", name: "Cuban Peso",          symbol: "$",     decimals: 2, region: "Americas" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc",   decimals: 2, region: "Africa" },
  { code: "CZK", name: "Czech Koruna",        symbol: "Kč",    decimals: 2, region: "Europe" },
  { code: "DJF", name: "Djiboutian Franc",    symbol: "Fr",    decimals: 0, region: "Africa" },
  { code: "DKK", name: "Danish Krone",        symbol: "kr",    decimals: 2, region: "Europe" },
  { code: "DOP", name: "Dominican Peso",      symbol: "RD$",   decimals: 2, region: "Americas" },
  { code: "DZD", name: "Algerian Dinar",      symbol: "د.ج",  decimals: 2, region: "Africa" },
  { code: "EGP", name: "Egyptian Pound",      symbol: "£",     decimals: 2, region: "Africa" },
  { code: "ERN", name: "Eritrean Nakfa",      symbol: "Nfk",   decimals: 2, region: "Africa" },
  { code: "ETB", name: "Ethiopian Birr",      symbol: "Br",    decimals: 2, region: "Africa" },
  { code: "EUR", name: "Euro",                symbol: "€",     decimals: 2, region: "Europe" },
  { code: "FJD", name: "Fijian Dollar",       symbol: "$",     decimals: 2, region: "Oceania" },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£",  decimals: 2, region: "Americas" },
  { code: "GBP", name: "British Pound",       symbol: "£",     decimals: 2, region: "Europe" },
  { code: "GEL", name: "Georgian Lari",       symbol: "₾",     decimals: 2, region: "Asia" },
  { code: "GHS", name: "Ghanaian Cedi",       symbol: "₵",     decimals: 2, region: "Africa" },
  { code: "GIP", name: "Gibraltar Pound",     symbol: "£",     decimals: 2, region: "Europe" },
  { code: "GMD", name: "Gambian Dalasi",      symbol: "D",     decimals: 2, region: "Africa" },
  { code: "GNF", name: "Guinean Franc",       symbol: "Fr",    decimals: 0, region: "Africa" },
  { code: "GTQ", name: "Guatemalan Quetzal",  symbol: "Q",     decimals: 2, region: "Americas" },
  { code: "GYD", name: "Guyanese Dollar",     symbol: "$",     decimals: 2, region: "Americas" },
  { code: "HKD", name: "Hong Kong Dollar",    symbol: "$",     decimals: 2, region: "Asia" },
  { code: "HNL", name: "Honduran Lempira",    symbol: "L",     decimals: 2, region: "Americas" },
  { code: "HRK", name: "Croatian Kuna",       symbol: "kn",    decimals: 2, region: "Europe" },
  { code: "HTG", name: "Haitian Gourde",      symbol: "G",     decimals: 2, region: "Americas" },
  { code: "HUF", name: "Hungarian Forint",    symbol: "Ft",    decimals: 2, region: "Europe" },
  { code: "IDR", name: "Indonesian Rupiah",   symbol: "Rp",    decimals: 2, region: "Asia" },
  { code: "ILS", name: "Israeli New Shekel",  symbol: "₪",     decimals: 2, region: "Middle East" },
  { code: "INR", name: "Indian Rupee",        symbol: "₹",     decimals: 2, region: "Asia" },
  { code: "IQD", name: "Iraqi Dinar",         symbol: "ع.د",  decimals: 3, region: "Middle East" },
  { code: "IRR", name: "Iranian Rial",        symbol: "﷼",     decimals: 2, region: "Middle East" },
  { code: "ISK", name: "Icelandic Króna",     symbol: "kr",    decimals: 0, region: "Europe" },
  { code: "JMD", name: "Jamaican Dollar",     symbol: "J$",    decimals: 2, region: "Americas" },
  { code: "JOD", name: "Jordanian Dinar",     symbol: "د.ا",  decimals: 3, region: "Middle East" },
  { code: "JPY", name: "Japanese Yen",        symbol: "¥",     decimals: 0, region: "Asia" },
  { code: "KES", name: "Kenyan Shilling",     symbol: "KSh",   decimals: 2, region: "Africa" },
  { code: "KGS", name: "Kyrgyzstani Som",     symbol: "с",     decimals: 2, region: "Asia" },
  { code: "KHR", name: "Cambodian Riel",      symbol: "៛",     decimals: 2, region: "Asia" },
  { code: "KMF", name: "Comorian Franc",      symbol: "Fr",    decimals: 0, region: "Africa" },
  { code: "KRW", name: "South Korean Won",    symbol: "₩",     decimals: 0, region: "Asia" },
  { code: "KWD", name: "Kuwaiti Dinar",       symbol: "د.ك",  decimals: 3, region: "Middle East" },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "$",   decimals: 2, region: "Americas" },
  { code: "KZT", name: "Kazakhstani Tenge",   symbol: "₸",     decimals: 2, region: "Asia" },
  { code: "LAK", name: "Lao Kip",             symbol: "₭",     decimals: 2, region: "Asia" },
  { code: "LBP", name: "Lebanese Pound",      symbol: "ل.ل",  decimals: 2, region: "Middle East" },
  { code: "LKR", name: "Sri Lankan Rupee",    symbol: "Rs",    decimals: 2, region: "Asia" },
  { code: "LRD", name: "Liberian Dollar",     symbol: "$",     decimals: 2, region: "Africa" },
  { code: "LSL", name: "Lesotho Loti",        symbol: "L",     decimals: 2, region: "Africa" },
  { code: "LYD", name: "Libyan Dinar",        symbol: "ل.د",  decimals: 3, region: "Africa" },
  { code: "MAD", name: "Moroccan Dirham",     symbol: "د.م.", decimals: 2, region: "Africa" },
  { code: "MDL", name: "Moldovan Leu",        symbol: "L",     decimals: 2, region: "Europe" },
  { code: "MGA", name: "Malagasy Ariary",     symbol: "Ar",    decimals: 2, region: "Africa" },
  { code: "MKD", name: "Macedonian Denar",    symbol: "ден",   decimals: 2, region: "Europe" },
  { code: "MMK", name: "Myanmar Kyat",        symbol: "K",     decimals: 2, region: "Asia" },
  { code: "MNT", name: "Mongolian Tögrög",    symbol: "₮",     decimals: 2, region: "Asia" },
  { code: "MOP", name: "Macanese Pataca",     symbol: "MOP$",  decimals: 2, region: "Asia" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM",    decimals: 2, region: "Africa" },
  { code: "MUR", name: "Mauritian Rupee",     symbol: "₨",     decimals: 2, region: "Africa" },
  { code: "MVR", name: "Maldivian Rufiyaa",   symbol: ".ރ",    decimals: 2, region: "Asia" },
  { code: "MWK", name: "Malawian Kwacha",     symbol: "MK",    decimals: 2, region: "Africa" },
  { code: "MXN", name: "Mexican Peso",        symbol: "$",     decimals: 2, region: "Americas" },
  { code: "MYR", name: "Malaysian Ringgit",   symbol: "RM",    decimals: 2, region: "Asia" },
  { code: "MZN", name: "Mozambican Metical",  symbol: "MT",    decimals: 2, region: "Africa" },
  { code: "NAD", name: "Namibian Dollar",     symbol: "$",     decimals: 2, region: "Africa" },
  { code: "NGN", name: "Nigerian Naira",      symbol: "₦",     decimals: 2, region: "Africa" },
  { code: "NIO", name: "Nicaraguan Córdoba",  symbol: "C$",    decimals: 2, region: "Americas" },
  { code: "NOK", name: "Norwegian Krone",     symbol: "kr",    decimals: 2, region: "Europe" },
  { code: "NPR", name: "Nepalese Rupee",      symbol: "₨",     decimals: 2, region: "Asia" },
  { code: "NZD", name: "New Zealand Dollar",  symbol: "$",     decimals: 2, region: "Oceania" },
  { code: "OMR", name: "Omani Rial",          symbol: "ر.ع.", decimals: 3, region: "Middle East" },
  { code: "PAB", name: "Panamanian Balboa",   symbol: "B/.",   decimals: 2, region: "Americas" },
  { code: "PEN", name: "Peruvian Sol",        symbol: "S/.",   decimals: 2, region: "Americas" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K",  decimals: 2, region: "Oceania" },
  { code: "PHP", name: "Philippine Peso",     symbol: "₱",     decimals: 2, region: "Asia" },
  { code: "PKR", name: "Pakistani Rupee",     symbol: "₨",     decimals: 2, region: "Asia" },
  { code: "PLN", name: "Polish Złoty",        symbol: "zł",    decimals: 2, region: "Europe" },
  { code: "PYG", name: "Paraguayan Guaraní",  symbol: "₲",     decimals: 0, region: "Americas" },
  { code: "QAR", name: "Qatari Riyal",        symbol: "ر.ق",  decimals: 2, region: "Middle East" },
  { code: "RON", name: "Romanian Leu",        symbol: "lei",   decimals: 2, region: "Europe" },
  { code: "RSD", name: "Serbian Dinar",       symbol: "дин.",  decimals: 2, region: "Europe" },
  { code: "RUB", name: "Russian Ruble",       symbol: "₽",     decimals: 2, region: "Europe" },
  { code: "RWF", name: "Rwandan Franc",       symbol: "Fr",    decimals: 0, region: "Africa" },
  { code: "SAR", name: "Saudi Riyal",         symbol: "ر.س",  decimals: 2, region: "Middle East" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "$",  decimals: 2, region: "Oceania" },
  { code: "SCR", name: "Seychellois Rupee",   symbol: "₨",     decimals: 2, region: "Africa" },
  { code: "SDG", name: "Sudanese Pound",      symbol: "£",     decimals: 2, region: "Africa" },
  { code: "SEK", name: "Swedish Krona",       symbol: "kr",    decimals: 2, region: "Europe" },
  { code: "SGD", name: "Singapore Dollar",    symbol: "$",     decimals: 2, region: "Asia" },
  { code: "SHP", name: "Saint Helena Pound",  symbol: "£",     decimals: 2, region: "Africa" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le",   decimals: 2, region: "Africa" },
  { code: "SOS", name: "Somali Shilling",     symbol: "S",     decimals: 2, region: "Africa" },
  { code: "SRD", name: "Surinamese Dollar",   symbol: "$",     decimals: 2, region: "Americas" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£",    decimals: 2, region: "Africa" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", decimals: 2, region: "Africa" },
  { code: "SVC", name: "Salvadoran Colón",    symbol: "$",     decimals: 2, region: "Americas" },
  { code: "SYP", name: "Syrian Pound",        symbol: "£",     decimals: 2, region: "Middle East" },
  { code: "SZL", name: "Eswatini Lilangeni",  symbol: "L",     decimals: 2, region: "Africa" },
  { code: "THB", name: "Thai Baht",           symbol: "฿",     decimals: 2, region: "Asia" },
  { code: "TJS", name: "Tajikistani Somoni",  symbol: "ЅМ",    decimals: 2, region: "Asia" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "m",     decimals: 2, region: "Asia" },
  { code: "TND", name: "Tunisian Dinar",      symbol: "د.ت",  decimals: 3, region: "Africa" },
  { code: "TOP", name: "Tongan Paʻanga",      symbol: "T$",    decimals: 2, region: "Oceania" },
  { code: "TRY", name: "Turkish Lira",        symbol: "₺",     decimals: 2, region: "Europe" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", decimals: 2, region: "Americas" },
  { code: "TWD", name: "New Taiwan Dollar",   symbol: "NT$",   decimals: 2, region: "Asia" },
  { code: "TZS", name: "Tanzanian Shilling",  symbol: "Sh",    decimals: 2, region: "Africa" },
  { code: "UAH", name: "Ukrainian Hryvnia",   symbol: "₴",     decimals: 2, region: "Europe" },
  { code: "UGX", name: "Ugandan Shilling",    symbol: "Sh",    decimals: 0, region: "Africa" },
  { code: "USD", name: "US Dollar",           symbol: "$",     decimals: 2, region: "Americas" },
  { code: "UYU", name: "Uruguayan Peso",      symbol: "$U",    decimals: 2, region: "Americas" },
  { code: "UZS", name: "Uzbekistani Som",     symbol: "сўм",   decimals: 2, region: "Asia" },
  { code: "VES", name: "Venezuelan Bolívar",  symbol: "Bs.",   decimals: 2, region: "Americas" },
  { code: "VND", name: "Vietnamese Đồng",     symbol: "₫",     decimals: 0, region: "Asia" },
  { code: "VUV", name: "Vanuatu Vatu",        symbol: "Vt",    decimals: 0, region: "Oceania" },
  { code: "WST", name: "Samoan Tala",         symbol: "T",     decimals: 2, region: "Oceania" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "Fr", decimals: 0, region: "Africa" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "$",   decimals: 2, region: "Americas" },
  { code: "XOF", name: "West African CFA Franc", symbol: "Fr", decimals: 0, region: "Africa" },
  { code: "XPF", name: "CFP Franc",           symbol: "₣",     decimals: 0, region: "Oceania" },
  { code: "YER", name: "Yemeni Rial",         symbol: "﷼",     decimals: 2, region: "Middle East" },
  { code: "ZAR", name: "South African Rand",  symbol: "R",     decimals: 2, region: "Africa" },
  { code: "ZMW", name: "Zambian Kwacha",      symbol: "ZK",    decimals: 2, region: "Africa" },
  { code: "ZWL", name: "Zimbabwean Dollar",   symbol: "$",     decimals: 2, region: "Africa" },
];

// Quick lookup helpers
export const ISO_CODES = ISO_4217.map((c) => c.code);
export const ISO_BY_CODE: Record<string, IsoCurrency> = Object.fromEntries(
  ISO_4217.map((c) => [c.code, c])
);

// Most common currencies (shown at the top of the dropdown)
export const ISO_TOP = ["USD", "EUR", "GBP", "INR", "JPY", "CNY", "AUD", "CAD", "CHF", "SGD"];
