// POST /api/v2/allocations/from-nl
// Body: { prompt: string }     — e.g. "Allocate IT cost across hospitals by patient bed count"
// Returns: { spec: AllocationSpec, reasoning: string }
//
// Uses Claude Haiku to translate plain English into a structured
// AllocationSpec. Returns a stub if ANTHROPIC_API_KEY isn't set.
import { NextRequest } from "next/server";
import { requireAuth } from "@/lib/api-helpers";
import { apiError, apiResponse } from "@/lib/utils";
import { prisma } from "@/lib/prisma";

const KEY = process.env.ANTHROPIC_API_KEY ?? "";

export async function POST(req: NextRequest) {
  const a = await requireAuth(req);
  if (a instanceof Response) return a;
  const { auth } = a;

  const body = await req.json().catch(() => null);
  if (!body?.prompt) return apiError("prompt is required", 400);

  // Gather context Claude needs: entity + account list
  const [entities, accounts] = await Promise.all([
    prisma.dimensionMember.findMany({
      where: { tenantId: auth.tid, dimension: { code: "entity" }, isActive: true },
      select: { memberCode: true, memberName: true }, take: 100,
    }),
    prisma.dimensionMember.findMany({
      where: { tenantId: auth.tid, dimension: { code: "account" }, isActive: true },
      select: { memberCode: true, memberName: true }, take: 200,
    }),
  ]);

  if (!KEY) {
    return apiResponse({
      spec: null,
      reasoning: "ANTHROPIC_API_KEY not set. Provide the spec manually via POST /api/v2/allocations/run.",
      context: { entityCount: entities.length, accountCount: accounts.length },
    });
  }

  const systemPrompt = `You are an FP&A allocation expert. Given a plain-English allocation request and the tenant's available entities + accounts, output a JSON AllocationSpec object — nothing else.

Available entities (code · name):
${entities.slice(0, 50).map(e => `  ${e.memberCode} · ${e.memberName}`).join("\n")}

Available accounts (code · name):
${accounts.slice(0, 50).map(a => `  ${a.memberCode} · ${a.memberName}`).join("\n")}

AllocationSpec shape:
{
  "sourceAccountCode":   string,  // existing account code
  "sourceEntityCode":    string,  // existing entity code
  "sourceScenarioCode":  string,  // e.g. "Actual"
  "sourcePeriodCode":    string,  // e.g. "FY2026" or "2026M04"
  "targetDim":           "ENTITY",
  "targetEntityCodes":   string[], // existing entity codes to allocate to
  "driver": {
    "kind": "EQUAL" | "FIXED_PCT" | "FACT_BASED",
    "pcts": { "ENT_CODE": number, ... },          // only if FIXED_PCT
    "factAccountCode":    string,                  // only if FACT_BASED
    "factScenarioCode":   string,                  // optional, defaults to source
    "factPeriodCode":     string                   // optional, defaults to source
  },
  "destAccountCode":  string?,    // optional
  "reverseSource":    boolean,    // true if source should be offset
  "notes":            string?
}

Use only codes that exist above. If the user is vague, pick reasonable defaults.`;

  try {
    const resp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": KEY, "anthropic-version": "2023-06-01" },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 1024,
        system: systemPrompt,
        messages: [{ role: "user", content: body.prompt }],
      }),
    });
    if (!resp.ok) {
      const errText = await resp.text();
      return apiError(`Claude error: ${resp.status} — ${errText.slice(0, 200)}`, 502);
    }
    const j = await resp.json();
    const text = j?.content?.[0]?.text ?? "";
    // Extract JSON block — Claude usually returns just the JSON, but be defensive
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) return apiResponse({ spec: null, reasoning: "Claude did not return parseable JSON", raw: text });
    let spec: any = null;
    try { spec = JSON.parse(match[0]); } catch (e: any) { return apiError("Generated spec is not valid JSON: " + e.message, 502); }
    return apiResponse({ spec, reasoning: "Generated by Claude Haiku from natural language.", raw: text });
  } catch (e: any) {
    return apiError("Claude call failed: " + e.message, 502);
  }
}
